version: '3.4'

networks:
  ansible:

services:
# Standard Nodes  
  control:
    hostname: 'control'
    container_name: control
    image: joshcliffordextend/centos-ansible:latest
    environment: 
      - ANSIBLE_CONFIG=./ansible.cfg
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./../ansible:/home/demo/ansible"
      - "./config/volume-files:/root/files"

  web01:
    hostname: 'web01'
    container_name: web01
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

  web02:
    hostname: 'web02'
    container_name: web02
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

  db01:
    hostname: 'db01'
    container_name: db01
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

  db02:
    hostname: 'db02'
    container_name: db02
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

# AWX Nodes
  awx_web:
    image: ansible/awx_web:latest
    container_name: awx_web
    networks:
      - ansible
    depends_on:
      - awx_rabbitmq
      - awx_memcached
      - awx_postgres
    ports:
      - "5001:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "./awx-config/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./awx-config/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./awx-config/credentials.py:/etc/tower/conf.d/credentials.py"
      # - "./awx-config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/volume1/docker-data/awx/projects:/var/lib/awx/projects:rw"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy:
    
  awx_task:
    image: ansible/awx_task:latest
    container_name: awx_task
    networks:
      - ansible
    depends_on:
      - awx_rabbitmq
      - awx_memcached
      - awx_web
      - awx_postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "./awx-config/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./awx-config/environment.sh:/etc/tower/conf.d/environment.sh"
      - "./awx-config/credentials.py:/etc/tower/conf.d/credentials.py"
      - "/volume1/docker-data/awx/projects:/var/lib/awx/projects:rw"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    
  awx_rabbitmq:
    image: ansible/awx_rabbitmq:latest
    container_name: awx_rabbitmq
    networks:
      - ansible
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: "awx"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "awxpass"
      RABBITMQ_ERLANG_COOKIE: cookiemonster
      http_proxy: 
      https_proxy: 
      no_proxy: 
    
  awx_memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    networks:
      - ansible
    restart: unless-stopped
    environment:
      http_proxy: 
      https_proxy: 
      no_proxy: 
    
  awx_postgres:
    image: postgres:10
    container_name: awx_postgres
    networks:
      - ansible
    restart: unless-stopped
    volumes:
      - /volume1/docker-data/awx/postgres/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
      http_proxy: 
      https_proxy: 
      no_proxy: