FROM centos:8
MAINTAINER Josh Clifford <jsclifford@envistiontechsolutions.com>

# Adding Tini init
ENV TINI_VERSION v0.19.0 
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

COPY config/creds.txt /tmp/creds.txt
COPY config/sshd_config /etc/ssh/sshd_config
COPY config/bin/* /usr/local/bin/
COPY dockerfile-script.sh /tmp/dockerfile-script.sh
COPY config/sshd_config /etc/ssh/sshd_config
COPY config/bin/* /usr/local/bin/
RUN /tmp/dockerfile-script.sh
RUN rm /tmp/dockerfile-script.sh

RUN mkdir -p /root/startup
COPY config/server-startup.sh /root/startup/server-startup.sh

EXPOSE 22
ENTRYPOINT ["/tini", "--"]

CMD ["/bin/bash","-c", "/root/startup/server-startup.sh"]

