version: '3.4'

networks:
  ansible:

services:
  control:
    hostname: 'control'
    image: joshcliffordextend/centos-ansible:latest
    environment: 
      - ANSIBLE_CONFIG=./ansible.cfg
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./../ansible:/home/demo/ansible"
      - "./config/volume-files:/root/files"

  web01:
    hostname: 'web01'
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

  web02:
    hostname: 'web02'
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

  db01:
    hostname: 'db01'
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"

  db02:
    hostname: 'db02'
    image: joshcliffordextend/centos-ansible:latest
    networks:
      - ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "./config/volume-files:/root/files"