# First ansible playbook
# Variable to roll back changes that can be overwritten on cli.
---
- name: Converted ad hoc command example
  hosts: all
  become: yes
  vars: 
    vstate: present
  tasks:
    - name: Setup Ansible Facts
      setup:
    - name: Display Ansible Facts
      debug:
        var: ansible_facts
    - name: user exists with UID 4000
      user:
        name: newbie
        uid: 4000
        state: "{{vstate}}"