---
- name: Deploy files using a Jinja2 template
  hosts: all
  become: true

  tasks:
    - name: Deploy the message of the day template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "644"
    - name: Deploy hosts file
    # Will Error due to docker host file locking.
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "644"
